#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Step 3.3: 生成 Oracle 控制改进前后对比表（NavSucc@8m/@4m，带95% CI）

用法示例：
  python scripts/analysis/oracle_control_improvement_table.py \
    --baseline logs_v2/proto_main_eval/oracle_proto_driven_30x5.jsonl \
    --improved logs_v2/proto_main_eval/oracle_proto_driven_30x5_improved_v2.jsonl \
    --out-md results/proto_main_eval/oracle_control_improvement_table.md \
    --out-tex results/proto_main_eval/oracle_control_improvement_table.tex
"""

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict, List, Tuple

# 让脚本在“直接python运行”时也能稳定导入同目录工具模块
THIS_FILE = Path(__file__).resolve()
PROJECT_ROOT = THIS_FILE.parents[2]  # .../scripts/analysis/ -> project root
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from scripts.analysis.statistics_utils import calculate_statistics_with_ci  # type: ignore
from scripts.analysis.unified_episode_evaluator import evaluate_episode  # type: ignore


def _load_jsonl(path: Path) -> List[Dict[str, Any]]:
    items: List[Dict[str, Any]] = []
    with open(path, "r", encoding="utf-8") as f:
        for line_no, line in enumerate(f, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                items.append(json.loads(line))
            except Exception as e:
                raise RuntimeError(f"Failed to parse JSONL at {path}:{line_no}: {e}") from e
    return items


def _extract_success_flags(eps: List[Dict[str, Any]]) -> Tuple[List[bool], List[bool]]:
    """
    统一口径：使用 Step 1 的 evaluate_episode() 计算 navsucc@{8,4}（基于 d_min < thr）。
    注意：日志字段 success_8m/success_4m 通常是 final_dist 判定，和我们统一口径不一致。
    """
    nav8: List[bool] = []
    nav4: List[bool] = []
    for ep in eps:
        ev = evaluate_episode(ep)
        nav8.append(bool(ev.get("navsucc8", False)))
        nav4.append(bool(ev.get("navsucc4", False)))
    return nav8, nav4


def _fmt_ci(stats: Dict[str, Any]) -> str:
    # 统一使用 “xx.x (CI: aa.a–bb.b)” 格式
    return stats["ci_string"]


def _make_md_row(name: str, s8: Dict[str, Any], s4: Dict[str, Any]) -> str:
    return f"| {name} | {_fmt_ci(s8)} | {_fmt_ci(s4)} |"


def _make_tex_row(name: str, s8: Dict[str, Any], s4: Dict[str, Any]) -> str:
    # LaTeX：用短横线 --；并保留一位小数
    def _tex_ci(st: Dict[str, Any]) -> str:
        return f"{st['mean_percent']:.1f}\\% ({st['ci_lower_percent']:.1f}--{st['ci_upper_percent']:.1f})"
    return f"{name} & {_tex_ci(s8)} & {_tex_ci(s4)} \\\\"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--baseline", type=str, required=True, help="baseline Oracle jsonl")
    ap.add_argument("--improved", type=str, required=True, help="improved Oracle jsonl")
    ap.add_argument("--out-md", type=str, default="results/proto_main_eval/oracle_control_improvement_table.md")
    ap.add_argument("--out-tex", type=str, default="results/proto_main_eval/oracle_control_improvement_table.tex")
    ap.add_argument("--ci-method", type=str, default="wilson", choices=["wilson", "bootstrap"])
    args = ap.parse_args()

    base_path = Path(args.baseline)
    imp_path = Path(args.improved)
    out_md = Path(args.out_md)
    out_tex = Path(args.out_tex)

    base_eps = _load_jsonl(base_path)
    imp_eps = _load_jsonl(imp_path)
    b8, b4 = _extract_success_flags(base_eps)
    i8, i4 = _extract_success_flags(imp_eps)

    b8s = calculate_statistics_with_ci(b8, method=args.ci_method)
    b4s = calculate_statistics_with_ci(b4, method=args.ci_method)
    i8s = calculate_statistics_with_ci(i8, method=args.ci_method)
    i4s = calculate_statistics_with_ci(i4, method=args.ci_method)

    out_md.parent.mkdir(parents=True, exist_ok=True)
    out_tex.parent.mkdir(parents=True, exist_ok=True)

    md_lines = [
        "## Oracle 控制改进前后对比（Step 3.3）",
        "",
        f"- baseline: `{base_path.as_posix()}` (n={len(base_eps)})",
        f"- improved: `{imp_path.as_posix()}` (n={len(imp_eps)})",
        f"- CI method: `{args.ci_method}`",
        "",
        "| Method | NavSucc@8m | NavSucc@4m |",
        "|---|---:|---:|",
        _make_md_row("Oracle (baseline)", b8s, b4s),
        _make_md_row("Oracle (improved)", i8s, i4s),
        "",
    ]
    out_md.write_text("\n".join(md_lines), encoding="utf-8")

    tex_lines = [
        "% Auto-generated by scripts/analysis/oracle_control_improvement_table.py",
        "\\begin{tabular}{lcc}",
        "\\toprule",
        "Method & NavSucc@8m & NavSucc@4m \\\\",
        "\\midrule",
        _make_tex_row("Oracle (baseline)", b8s, b4s),
        _make_tex_row("Oracle (improved)", i8s, i4s),
        "\\bottomrule",
        "\\end{tabular}",
        "",
    ]
    out_tex.write_text("\n".join(tex_lines), encoding="utf-8")

    print(f"[OK] wrote md : {out_md}")
    print(f"[OK] wrote tex: {out_tex}")


if __name__ == "__main__":
    main()


